type Text = string;
export type Comment = {
    externalProviderType:string,
    entityType:string,
    compositeId:string,
    id:string,
    replyOwnerId:string,
    commentsCount:number,
    location:Text,
    date:Date|string,
    likesCount:number,
    replyUserId:string,
    replyToPostId:string,
    lang:string,
    place:Text,
    quotedPostId:string,
    quotedPost:string,
    repostsCount:number,
    platform:string,
    text:Text,
    url:string,
    link:string,
    linkName:string,
    linkImage:string,
    replyToCommentId:string
}