type Text = string;
export type Group = {
    id?:string,
    extraData?:Text,
    name?:string,
    screenName?:string,
    email?:string,
    country?:Text,
    location?:Text,
    city?:Text,
    address?:string,
    type?:string,
    description?:string,
    phone?:string,
    private_?:boolean,
    premium?:boolean,
    verified?:boolean,
    homePage?:string,
    homePageName?:string,
    membersCount?:number,
    //эти поля для групп-событий?
    ageFrom?:number,
    dateFrom?:Date,
    dateTo?:Date,
    //---------------------------
    dateUpdated?:Date,
    dateLabel?:string,
    photo?:string,
    photoSmall?:string,
    photoMedium?:string,
    photoLarge?:string,
    admin?:string,
    deleted?:boolean,
    status?:string,
    groupPrivacy?:string,
    registeredDate?:Date|string,
    followersCount?:number
}