import { TPostPage } from "./Posts";

export const PostsTestData : TPostPage[] = [ { commentsCount: 2,
    date: '2018-07-21T23:28:00.000Z',
    extraData: null,
    feedCount: { likes: 47, love: 2, wow: null },
    lang: null,
    linkImage: null,
    quotedPost: { Id: null, value: null },
    repostsCount: null },
  { commentsCount: 8,
    date: '2018-07-16T22:22:00.000Z',
    extraData: null,
    feedCount: { likes: 99, love: 6, wow: null },
    lang: null,
    linkImage: null,
    quotedPost: { Id: null, value: null },
    repostsCount: null },
  { commentsCount: 5,
    date: '2018-06-30T18:53:00.000Z',
    extraData: null,
    feedCount: { likes: 38, love: 13, wow: null },
    lang: null,
    linkImage: null,
    quotedPost: { Id: null, value: null },
    repostsCount: null,
    url: 'https://www.facebook.com/bibian.pinto/posts/2138724869691327' },
  { commentsCount: null,
    date: null,
    extraData: null,
    feedCount: { likes: null, love: null, wow: null },
    lang: null,
    linkImage: null,
    place: null,
    quotedPost: { Id: null, value: null },
    repostsCount: null,
    url: null },
  { commentsCount: null,
    date: '2018-06-26T20:28:00.000Z',
    extraData: null,
    feedCount: { likes: 22, love: 2, wow: null },
    lang: null,
    linkImage: null,
    quotedPost: { Id: null, value: null },
    repostsCount: 1,
    url: 'https://www.facebook.com/kh7ir/posts/2079062269082912' },
  { commentsCount: null,
    date: '2018-06-13T21:45:00.000Z',
    extraData: null,
    feedCount: { likes: 5, love: null, wow: null },
    lang: null,
    linkImage: null,
    quotedPost: { Id: null, value: null },
    repostsCount: null,
    url: 'https://www.facebook.com/kh7ir/posts/2066076500381489' },
  { commentsCount: 8,
    date: '2018-06-07T13:55:00.000Z',
    extraData: null,
    feedCount: { likes: 100, love: 4, wow: null },
    lang: null,
    linkImage: null,
    quotedPost: { Id: null, value: null },
    repostsCount: null } ];